---
- hosts: masters
  become: yes
  tasks:
    - name: Get join command
      shell: kubeadm token create --print-join-command
      register: join_command

    - name: Save join command to a file
      copy:
        content: sudo {{ join_command.stdout }}
        dest: /home/vagrant/join_command.sh
      become_user: vagrant

    - name: Fetch the file from remote server
      fetch:
        src: /home/vagrant/join_command.sh
        dest: /tmp/join_command.sh
        flat: yes

- hosts: workers
  become: yes
  tasks:
    - name: Copy join command from master
      copy:
        src: /tmp/join_command.sh
        dest: /tmp/join_command.sh

    - name: Execute join command
      shell: sh /tmp/join_command.sh

