apiVersion: v1
kind: Service
metadata:
  name: nats-cluster
  namespace: nats
spec:
  clusterIP: None  # Headless service
  ports:
    - name: client
      port: 4222
      targetPort: 4222
    - name: cluster
      port: 6222
      targetPort: 6222
  selector:
    app: nats
